name: Build Application

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build and run containers
        run: |
          nohup docker compose up &

      - name: Instalar Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 18

      - name: Instalar dependencias
        run: npm install
        working-directory: ./Backend

      - name: instalar mocha
        run: npm install --save-dev mocha 
        working-directory: ./Backend

      - name: esperar
        run: sleep 60

      - name: Correr backend
        run: nohup node index.js &    # Ejecuta la aplicación en segundo plano
        working-directory: ./Backend

      - name: Correr Tests
        run: |
          export DB_HOST=localhost
          (timeout 10 npx mocha Tests.js || true)
          if [ "$(timeout 10 npx mocha Tests.js | grep -c '5 passing')" -eq 1 ]; then
            echo "Tests pasaron exitosamente."
          else
            echo "Los tests no pasaron. Terminando el flujo de trabajo."
            exit 1
          fi
        working-directory: ./Backend



