name: Build Applicationn

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build and run FRONT
        working-directory: ./Frontend
        run: |
           nohup docker build -t front . &
           sleep 10
           
      - name: Build and run DATABASE
        working-directory: ./Database
        run: |
           nohup docker build -t database . &
           docker run -d --name mydb -p 3306:3306

      - name: esperar
        run: |
          sleep 90

      - name: Build and run BACK
        working-directory: ./Backend
        run: |
           nohup docker build -t back . &

      - name: Correr Tests
        run: |
          chmod +x ./node_modules/.bin/mocha
          npx mocha Tests.js
        working-directory: ./Backend

      - name: Login to Docker Hub
        run: docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_PASSWORD }}
      
      - name: Tag and push Docker images
        run: |
          docker tag integradoringsw3-backend:latest ${{ secrets.DOCKERHUB_USERNAME }}/integradoringsw3-backend:latest
          docker tag integradoringsw3-frontend:latest ${{ secrets.DOCKERHUB_USERNAME }}/integradoringsw3-frontend:latest
          docker tag mysql:latest ${{ secrets.DOCKERHUB_USERNAME }}/mysql:latest

          docker push ${{ secrets.DOCKERHUB_USERNAME }}/integradoringsw3-backend:latest
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/integradoringsw3-frontend:latest
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/mysql:latest
          




