name: Build Application

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker
        run: |
          sudo apt-get update
          sudo apt-get install apt-transport-https ca-certificates curl software-properties-common -y
          curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
          sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
          sudo apt-get update
          sudo apt-get install docker-ce -y

      - name: Build and run containers
        run: |
          docker-compose up -d

      - name: Instalar Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 18

      - name: Instalar dependencias
        run: npm install
        working-directory: ./Backend

      - name: intalar mocha
        run: npm install --save-dev mocha 
        working-directory: ./Backend

      - name: Correr backend
        run: nohup node index.js &    # Ejecuta la aplicación en segundo plano
        working-directory: ./Backend

      - name: Correr Tests
        run: |
          export DB_HOST=localhost

          
          chmod +x ./node_modules/.bin/mocha

          
          (timeout 10 ./node_modules/.bin/mocha Tests.js || true)
          if [ "$(timeout 10 ./node_modules/.bin/mocha Tests.js | grep -c '5 passing')" -eq 1 ]; then
            echo "Tests pasaron exitosamente."
          else
            echo "Los tests no pasaron. Terminando el flujo de trabajo."
            exit 1
          fi
        working-directory: ./Backend




