name: Build Applicationn

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build and run containers
        run: |
          nohup docker compose up &

      - name: esperar
        run: sleep 60

      - name: Correr Tests
        run: |
          chmod +x ./node_modules/.bin/mocha
          npx mocha Tests.js
        working-directory: ./Backend

      - name: Login to Docker Hub
        run: docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_PASSWORD }}
      
      - name: Tag and push Docker images
        run: |
          docker tag integradoringsw3-backend:latest ${{ secrets.DOCKERHUB_USERNAME }}/integradoringsw3-backend:latest
          docker tag integradoringsw3-frontend:latest ${{ secrets.DOCKERHUB_USERNAME }}/integradoringsw3-frontend:latest
          docker tag mysql:latest ${{ secrets.DOCKERHUB_USERNAME }}/mysql:latest

          docker push ${{ secrets.DOCKERHUB_USERNAME }}/integradoringsw3-backend:latest
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/integradoringsw3-frontend:latest
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/mysql:latest
          




