name: Deploy to Cloud Run

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        run: docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Pull Docker images
        run: |
          docker pull ${{ secrets.DOCKERHUB_USERNAME }}/integradoringsw3-backend:latest
          docker pull ${{ secrets.DOCKERHUB_USERNAME }}/integradoringsw3-frontend:latest
          docker pull ${{ secrets.DOCKERHUB_USERNAME }}/mysql:latest

      - name: Configure gcloud SDK
        uses: google-github-actions/auth@v0
        with:
          credentials_json: ${{ secrets.GCLOUD_SERVICE_KEY }}
          project_id: ${{ secrets.GCLOUD_PROJECT_ID }}

      - name: Deploy to Cloud Run Backend
        run: |
          gcloud run deploy integradoringsw3-backend --image=${{ secrets.DOCKERHUB_USERNAME }}/integradoringsw3-backend:latest --platform=managed

      - name: Deploy to Cloud Run Frontend
        run: |
          gcloud run deploy integradoringsw3-frontend --image=${{ secrets.DOCKERHUB_USERNAME }}/integradoringsw3-frontend:latest --platform=managed

      - name: Deploy to Cloud Run MySQL
        run: |
          gcloud run deploy mysql --image=${{ secrets.DOCKERHUB_USERNAME }}/mysql:latest --platform=managed
