name: Deploy to Cloud Run

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to Heroku Container Registry
        run: echo ${{ secrets.HEROKU_API_KEY }} | docker login -u=_ --password-stdin registry.heroku.com

      - name: Login to Heroku CLI
        run: |
          echo "${{ secrets.HEROKU_API_KEY }}" | base64 --decode | heroku login --interactive
          heroku container:login


