name: Deploy to Cloud Run

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Instalar Heroku CLI
        run: |
          curl https://cli-assets.heroku.com/install.sh | sh

      - name: Inicio de sesión en Heroku
        run: heroku login -i

      - name: Configuración de la clave API de Heroku
        run: heroku git:remote -a ingsw3
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
          
      - name: Cargar imagen 
        working-directory: ./Backend  
        run: |
          heroku container:login
          docker build -t registry.heroku.com/ingsw3/web .
          docker push registry.heroku.com/ingsw3/web

      - name: Desplegar imagen en Heroku
        run: heroku container:release web -a ingsw3
