name: Deploy to Cloud Run

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to Heroku Container Registry
        run: echo ${{ secrets.HEROKU_API_KEY }} | docker login -u=_ --password-stdin registry.heroku.com

      - name: Configure Heroku CLI
        run: |
          echo -e "machine api.heroku.com\n  login $HEROKU_EMAIL\n  password $HEROKU_API_KEY\nmachine git.heroku.com\n  login $HEROKU_EMAIL\n  password $HEROKU_API_KEY" > ~/.netrc
      
      - name: Build and push Docker image
        working-directory: ./Backend 
        run: |
          docker build -t backend .
          docker tag backend registry.heroku.com/ingsw3/web
          docker push registry.heroku.com/ingsw3/web

      - name: Build and push Docker image for frontend
        working-directory: ./Frontend
        run: |
          docker build -t frontend .
          docker tag frontend registry.heroku.com/ingsw3/web
          docker push registry.heroku.com/your-heroku-app-frontend/web

      - name: Release frontend to Heroku
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        run: heroku container:release web -a your-heroku-app-frontend

      - name: Release to Heroku
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        run: heroku container:release web -a ingsw3
        
      - name: Activate Deployment on Heroku
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        run: heroku ps:scale web=1 -a ingsw3
